name: CI
on: [pull_request, workflow_dispatch, push]

jobs:
  build_windows_clang:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
      - uses: seanmiddleditch/gha-setup-ninja@master

      - uses: leafo/gh-actions-lua@v10
        with:
          luaVersion: "5.3.0"

      - name: Download Submodules
        run: git submodule update --init --recursive

      - name: Build Cuik
        shell: cmd
        timeout-minutes: 10
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat
          luajit build.lua

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cuik-windows
          path: cuik.exe
  build_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Download Lua
        run: |
          brew update
          brew install lua@5.3

      - name: Download LLVM
        run: |
          brew install llvm@14

      - name: Download Submodules
        run: git submodule update --init --recursive

      - name: Build Cuik
        run: lua build.lua
        timeout-minutes: 10

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cuik-macos
          path: cuik
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Download LLVM & Lua
        run: sudo apt-get install llvm-11 clang-11 lld lua5.3

      - name: Download Submodules
        run: git submodule update --init --recursive

      - name: Build Cuik
        run: lua build.lua
        timeout-minutes: 10

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cuik-linux
          path: cuik
