name: Run Tests
on: [push, pull_request, workflow_dispatch]

jobs:
  test_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Clang
        run: sudo apt-get install clang

      - name: Build Cuik
        run: sh ./build_cuik.sh
        timeout-minutes: 10
