name: CI
on: [pull_request, workflow_dispatch, push]

jobs:
  build_windows_clang:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v1
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Download Submodules
        run: git submodule update --init --recursive

      - name: Build Cuik
        shell: cmd
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat
          python build.py -opt
        timeout-minutes: 10

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cuik-windows
          path: cuik.exe
  build_mac:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v1
      - uses: seanmiddleditch/gha-setup-ninja@master
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Download LLVM
        run: |
          brew update
          brew install llvm@14

      - name: Download Submodules
        run: git submodule update --init --recursive

      - name: Build Cuik
        run: python3 build.py -opt
        timeout-minutes: 10

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cuik-macos
          path: cuik
  build_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: seanmiddleditch/gha-setup-ninja@master
      - name: Download LLVM
        run: sudo apt-get install llvm-11 clang-11 lld

      - name: Download Submodules
        run: git submodule update --init --recursive

      - name: Build Cuik
        run: python build.py -opt
        timeout-minutes: 10

      - name: upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: cuik-linux
          path: cuik