name: Run Tests
on: [push, pull_request, workflow_dispatch]

jobs:
  test_linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Download Clang
        run: sudo apt-get install clang

      - name: Download Ninja
        run: sudo apt-get install ninja-build

      - name: Download Submodules
        run: git submodule update --init --recursive

      - name: Build Cuik
        run: sh ./build.sh
        timeout-minutes: 10
