name: Run Tests
on: [push, pull_request, workflow_dispatch]

jobs:
  test_linux:
    runs-on: windows-2019
    steps:
      - uses: actions/checkout@v2
      - uses: seanmiddleditch/gha-setup-ninja@master

      - name: Download Submodules
        run: git submodule update --init --recursive

      - name: Build Cuik
        working-directory: main
        run: |
          call "C:\Program Files (x86)\Microsoft Visual Studio\2019\Enterprise\VC\Auxiliary\Build\vcvars64.bat"
          py build.py
        timeout-minutes: 10
